package ee.app.conversamanager.actions;

/**
 * Created by edgargomez on 10/4/16.
 */

public enum MessageAction {
    ACTION_MESSAGE_OUTGOING,
    ACTION_MESSAGE_INCOMING,
    ACTION_MESSAGE_DELETE,
    ACTION_MESSAGE_DELETE_MULTIPLE,
    ACTION_MESSAGE_DELETE_ALL,
    ACTION_MESSAGE_RETRIEVE_ALL,
    ACTION_MESSAGE_UPDATE_STATUS,
    ACTION_MESSAGE_UPDATE_VIEW,
    ACTION_MESSAGE_UPDATE_READ,
    ACTION_MESSAGE_UPDATE_DOWNLOAD,
    ACTION_MESSAGE_UPDATE_DOWNLOAD_FAILED
}